import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import Collections from "views/collections/Collections";

const CollectionPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NFT collections | My Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Collections />
    </div>
  );
};

export default CollectionPage;
