import type { NextPage } from "next";
import Head from "next/head";
import {
  Clans,
  Creators,
  Earth,
  Features,
  HomeIntro,
  MeetPlatoon,
  StakeShop,
} from "views/home";

const Home: NextPage = () => {
  return (
    <div style={{ paddingTop: "71px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomeIntro />
      <StakeShop />
      <Earth />
      <MeetPlatoon />
      <Features />
      <Clans />
      <Creators />
    </div>
  );
};

export default Home;
