import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import {
  Community,
  FAQ,
  Featured,
  LaunchPadLanding,
  Pricing,
  RevenueSharing,
} from "views/launchpad";

const LaunchpadPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Platoon Launchpad | My Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <LaunchPadLanding />
      <Featured />
      <Pricing />
      <Community />
      <RevenueSharing />
      <FAQ /> */}
    </div>
  );
};

export default LaunchpadPage;
