import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import { LaunchPadLanding } from "views/launchpad";

const LaunchpadPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Platoon Launchpad | My Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LaunchPadLanding />
    </div>
  );
};

export default LaunchpadPage;
