import React from "react";
import { NextPage } from "next";
import Head from "next/head";

const PetePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Platoon Launchpad | My Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
};

export default PetePage;
